# Generated by Django 5.2.1 on 2025-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128, null=True)),
                ('preferred_lang', models.CharField(choices=[('EN', 'English'), ('BE', 'Belarusian'), ('PL', 'Polish'), ('RU', 'Russian')], default='EN', max_length=2)),
            ],
        ),
    ]
